### ISSUE TITLE
Enable disabling of leveling?

### ISSUE THREAD

**Issue by LafuenteAstronomy** [UtopicUnicorns/mint-bot#5]
There might be a possibility that some members and admins of servers want the characteristics of Artemis in modding and admining, but not the leveling. MEE6 has a way to disable leveling, can you add that to Artemis as well? 

I joined a new server and I added Artemis there but the founder does not want any leveling.

**Comment by UtopicUnicorns** [comment]
sure i'll add it in a moment

**Comment by UtopicUnicorns** [comment]
Done
